#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# the "app_vex_parser" route name is not important yet
app_vex_team_list:
    path: /vex/web_parser/team_list/{name}
    controller: App\Controller\VEXWebParserController::parseTeamListFromEvent
app_vex_team_awards:
    path: /vex/web_parser/team_awards/{name}
    controller: App\Controller\VEXWebParserController::fetchTeamAwards